lua
Copy code
[build]
  command = "ng build --prod && npm run json-server"
  publish = "dist/nombre-de-tu-app"

[dev]
  command = "ng serve --open"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3000/:splat"
  status = 200